# Homebrew formula for the `adoc` AsciiDoc processor.
#
# Generated by .github/workflows/release.yml — every successful release
# replaces this file with the version number and SHA256s of the freshly
# published archives. Manual edits are overwritten on the next release.
#
#   brew install grahambrooks/adoc/adoc
#
# Windows users: Homebrew has no Windows support; grab the
# adoc-2026.9.9-x86_64-pc-windows-msvc.zip archive from the Releases page.
class Adoc < Formula
  desc "Rust command-line processor for the AsciiDoc Language specification"
  homepage "https://github.com/grahambrooks/adoc"
  version "2026.9.9"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/grahambrooks/adoc/releases/download/2026.9.9/adoc-2026.9.9-aarch64-apple-darwin.tar.gz"
      sha256 "7ac745689cd6ca7eff71c62195505567ac6592f9cc70f8fee41285bcfcbaa868"
    else
      url "https://github.com/grahambrooks/adoc/releases/download/2026.9.9/adoc-2026.9.9-x86_64-apple-darwin.tar.gz"
      sha256 "c2c05f017311e64e6ccf59669325f86e18a82bfac9eba1eb39e93bed848dead6"
    end
  end

  on_linux do
    url "https://github.com/grahambrooks/adoc/releases/download/2026.9.9/adoc-2026.9.9-x86_64-unknown-linux-gnu.tar.gz"
    sha256 "e091457e62d2821eefda33fcbfb25a6e355adc0bba7e297996c6332088e174cf"
  end

  def install
    bin.install "adoc"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/adoc --version")
  end
end
