# Generated by scripts/release.py (release-kit) from the v2026.10.1 release — do not edit.
class Adoc < Formula
  desc "Rust command-line processor for the AsciiDoc Language specification"
  homepage "https://github.com/grahambrooks/adoc"
  version "2026.10.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/adoc/releases/download/v2026.10.1/adoc-v2026.10.1-aarch64-apple-darwin.tar.gz"
      sha256 "95617133a104d0cf6835c5164862dd17babc4facf31ab5c8354abcbb938c64eb"
    end
    on_intel do
      url "https://github.com/grahambrooks/adoc/releases/download/v2026.10.1/adoc-v2026.10.1-x86_64-apple-darwin.tar.gz"
      sha256 "03d0245ec08709d4ebde5a46bcde647a95785e45764ed7efd6675bff2d254988"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahambrooks/adoc/releases/download/v2026.10.1/adoc-v2026.10.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "4fa889cad75c2ac096bfd354924e9ab0608325d4c6cf93565f49e6f523183536"
    end
    on_intel do
      url "https://github.com/grahambrooks/adoc/releases/download/v2026.10.1/adoc-v2026.10.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "e8ca9de465587e6190e842f0ead8a074bf658a0ba884cabb2a3c70ee20d92df4"
    end
  end

  def install
    bin.install "adoc"
  end

  test do
    assert_path_exists bin/"adoc"
  end
end
