# Generated by scripts/release.py (release-kit) from the v2026.9.10 release — do not edit.
class Adoc < Formula
  desc "Rust command-line processor for the AsciiDoc Language specification"
  homepage "https://github.com/grahambrooks/adoc"
  version "2026.9.10"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/adoc/releases/download/v2026.9.10/adoc-v2026.9.10-aarch64-apple-darwin.tar.gz"
      sha256 "fe99df8d1aabe762df65a8d3611b4dcb7ec2bb3cffcab88818ddb3706587fe3c"
    end
    on_intel do
      url "https://github.com/grahambrooks/adoc/releases/download/v2026.9.10/adoc-v2026.9.10-x86_64-apple-darwin.tar.gz"
      sha256 "6fc4bdcacff6b5b680f6851f13547b375238cda8c68bbce040b157fc2b3e572a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahambrooks/adoc/releases/download/v2026.9.10/adoc-v2026.9.10-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "eec6aa8d47fbfc524d535c79a2c7bddbf0050814c45d8636dc58c6a50925ebaa"
    end
    on_intel do
      url "https://github.com/grahambrooks/adoc/releases/download/v2026.9.10/adoc-v2026.9.10-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "94ce28b5d9a9deac476ee69002fb2438fe4f3c8a9547f37dd7af4913980fe58f"
    end
  end

  def install
    bin.install "adoc"
  end

  test do
    assert_path_exists bin/"adoc"
  end
end
